<a href="https://colab.research.google.com/github/bachi-mohamed-rafik/ML_intro/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PYTORCH

In [1]:
import torch

In [2]:
#Create a Tensor
New_Tensor=torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
print(New_Tensor)
#Create a tensor with onlty dimensions
Next_Tensor=torch.Tensor(3,5)
print(Next_Tensor)


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[3.4021e-36, 0.0000e+00, 5.0447e-44, 0.0000e+00,        nan],
        [0.0000e+00, 1.3788e-14, 1.8369e+28, 1.9433e-19, 3.3738e-12],
        [7.4086e+28, 6.9397e+22, 1.7260e+25, 2.2856e+20, 5.0948e-14]])


In [3]:
#Create a multy dimensional Tensor with uniform values
uniform_tensor=torch.Tensor(5,2).uniform_(2,3)
print(uniform_tensor)

tensor([[2.5078, 2.3707],
        [2.7393, 2.1547],
        [2.5333, 2.0684],
        [2.8196, 2.6028],
        [2.7681, 2.1861]])


In [11]:
#Create tensor xith random values
rand_tensor=torch.rand(5,4)
print(rand_tensor)

tensor([[0.6641, 0.0204, 0.3880, 0.0562],
        [0.0384, 0.0020, 0.8135, 0.7148],
        [0.5415, 0.5901, 0.4874, 0.1699],
        [0.8328, 0.2109, 0.9732, 0.1601],
        [0.6629, 0.0525, 0.5569, 0.1374]])


In [5]:
# Create a zeros tensor
zeros_tensor=torch.zeros(5,4)
print("zeros_tensor: \n",zeros_tensor)

# Create a ones tensor
ones_tensor=torch.ones(5,4)
print("ones_tensor:\n",ones_tensor)

zeros_tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones_tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [6]:
#Get value in Tensor
new_tensor=torch.Tensor([[2,3],[4,5]])
print("methode 1 : \n",new_tensor[0][0])
print("methode 2 : \n",new_tensor[0][0].item())

methode 1 : 
 tensor(2.)
methode 2 : 
 2.0


In [7]:
#Change a specific value in tensor
new_tensor[1][0]=5
print(new_tensor)

tensor([[2., 3.],
        [5., 5.]])


In [8]:
#Slicing from tensor
slicing_tensor=torch.Tensor([[1,2,3],[5,6,5],[5,8,7],[5,7,8],[2,8,8]])
print("Slicing the 3rd column ",slicing_tensor[:,2])
print("Slicing the 3rd row ",slicing_tensor[2,:])
print("Slicing the 3 first rows ",slicing_tensor[:2,:])

Slicing the 3rd column  tensor([3., 5., 7., 8., 8.])
Slicing the 3rd row  tensor([5., 8., 7.])
Slicing the 3 first rows  tensor([[1., 2., 3.],
        [5., 6., 5.]])


In [9]:
#type
print(type(new_tensor))

#shape
print(new_tensor.shape)

#size or dimension
print(new_tensor.size)
print(new_tensor.dim)

#View
print(new_tensor.view(1,4))

<class 'torch.Tensor'>
torch.Size([2, 2])
<built-in method size of Tensor object at 0x7fa51407d750>
<built-in method dim of Tensor object at 0x7fa51407d750>
tensor([[2., 3., 5., 5.]])


#Operation to Tesor

In [ ]:
#adding
x=torch.rand(4,5)
y=torch.rand(4,5)
# methode 1 
print(x+y)

# methode 2
print(torch.add(x,y))

# methode 3
result=torch.empty(4,5)
print(torch.add(x,y,out=result))

tensor([[1.0349, 1.1574, 0.8684, 0.9679, 0.5245],
        [0.4407, 0.9771, 0.8708, 0.5253, 1.2466],
        [0.3836, 1.4466, 1.0218, 1.1646, 1.0863],
        [1.8310, 0.8468, 1.2847, 0.0314, 1.4835]])
tensor([[1.0349, 1.1574, 0.8684, 0.9679, 0.5245],
        [0.4407, 0.9771, 0.8708, 0.5253, 1.2466],
        [0.3836, 1.4466, 1.0218, 1.1646, 1.0863],
        [1.8310, 0.8468, 1.2847, 0.0314, 1.4835]])
tensor([[1.0349, 1.1574, 0.8684, 0.9679, 0.5245],
        [0.4407, 0.9771, 0.8708, 0.5253, 1.2466],
        [0.3836, 1.4466, 1.0218, 1.1646, 1.0863],
        [1.8310, 0.8468, 1.2847, 0.0314, 1.4835]])


In [ ]:
#Transpose a matrix
x=torch.randn(5,5)
print("The initial matrix :\n",x)

#Meth 1
print("Meth 1 :\n",x.t())

print("Meth 2 :\n",x.permute(-1,0))

The initial matrix :
 tensor([[-0.6458, -0.5212,  2.8516,  0.4548,  0.1700],
        [-0.9856,  0.2036,  0.4673, -0.0200, -0.0453],
        [-0.6881, -0.2457,  1.5553,  0.4280,  0.1296],
        [ 0.9021,  0.6072,  1.5612,  0.0769, -0.4134],
        [ 3.0418,  1.1258, -1.1002,  0.5187,  0.6400]])
Meth 1 :
 tensor([[-0.6458, -0.9856, -0.6881,  0.9021,  3.0418],
        [-0.5212,  0.2036, -0.2457,  0.6072,  1.1258],
        [ 2.8516,  0.4673,  1.5553,  1.5612, -1.1002],
        [ 0.4548, -0.0200,  0.4280,  0.0769,  0.5187],
        [ 0.1700, -0.0453,  0.1296, -0.4134,  0.6400]])
Meth 2 :
 tensor([[-0.6458, -0.9856, -0.6881,  0.9021,  3.0418],
        [-0.5212,  0.2036, -0.2457,  0.6072,  1.1258],
        [ 2.8516,  0.4673,  1.5553,  1.5612, -1.1002],
        [ 0.4548, -0.0200,  0.4280,  0.0769,  0.5187],
        [ 0.1700, -0.0453,  0.1296, -0.4134,  0.6400]])


In [ ]:
#Matrix Multiplication
t1=torch.randn(5,5)
t2=torch.randn(5,5)
m_prod=t1.mm(t2)
print(m_prod)

tensor([[ 4.5386, -3.7414,  0.3585,  5.5628, -1.9581],
        [ 3.7522, -2.5359, -1.3224,  3.1706, -1.4481],
        [ 0.7749, -0.4994,  1.8141,  0.6502,  0.0960],
        [-2.8234, -1.8252, -0.6911, -0.2864, -1.6196],
        [ 0.6810,  2.7605,  0.4081, -2.6811, -0.2311]])


In [ ]:
#Convert numpy to pytorch
import numpy as np
np_arr=np.random.randn(5,5)
print(np_arr)
np_ts=torch.from_numpy(np_arr)
print(np_ts)

[[-0.22589277 -1.47432499  0.27110843 -0.96685583 -0.8737127 ]
 [ 0.76071477 -0.75383472 -0.50614829 -1.07733635 -2.08826446]
 [ 1.59845692  0.90333872 -1.56408916  1.36400553  0.01457134]
 [ 0.18635342  1.39328145  1.47839024 -1.49625161 -0.26856152]
 [ 2.24614545  1.42581802 -0.16510268  0.03701617  0.01608703]]
tensor([[-0.2259, -1.4743,  0.2711, -0.9669, -0.8737],
        [ 0.7607, -0.7538, -0.5061, -1.0773, -2.0883],
        [ 1.5985,  0.9033, -1.5641,  1.3640,  0.0146],
        [ 0.1864,  1.3933,  1.4784, -1.4963, -0.2686],
        [ 2.2461,  1.4258, -0.1651,  0.0370,  0.0161]], dtype=torch.float64)


In [ ]:
#Convert pytorch to numpy
to_np=np_ts.numpy()
print(to_np)

[[-0.22589277 -1.47432499  0.27110843 -0.96685583 -0.8737127 ]
 [ 0.76071477 -0.75383472 -0.50614829 -1.07733635 -2.08826446]
 [ 1.59845692  0.90333872 -1.56408916  1.36400553  0.01457134]
 [ 0.18635342  1.39328145  1.47839024 -1.49625161 -0.26856152]
 [ 2.24614545  1.42581802 -0.16510268  0.03701617  0.01608703]]
